feat:개인 뒹글 페이지 조회 구현
dooingledooingle/dooingle pull request #27
Opened 2024-03-03 13:25 UTC by kDAJIN

## 연관 이슈
- closes #23 

## 해당 작업을 한 동기/이유는 무엇인가요?
- 내 뒹글페이지('오너'에게 온 뒹글과 캐치)를 볼 수 있는 페이지를 구현하기 위해 작업하다가 
  오너가 보는 뒹글 페이지가 다른 유저가 보는 오너의 개인페이지가 다르지않다는 생각이 들어 개인페이지로 명칭을 바꿔 작업하였습니다.

## 리뷰어에게 작업 또는 변경 내용을 상세히 설명해주세요
- [ ] 뒹글과 캐치의 관계를 one to one 관계로 수정
- [ ] 페이지 조회시 삭제(소프트딜리트)된 캐치의 컨텐트를  노출시키지 않기 위해서 뒹글리스폰스에 딜리티드엣의 존재를 검증하는 로직을 추가함
    - 딜리티드엣이 널값인 경우 정상적으로 컨텐트 노출, 널값이 아닌 경우 "삭제된 캐치입니다." 노출

2024-03-03 15:43 UTC, adorecamus reviewed
주말인데 정말 고생하셨습니다!! 🥹❤️
그런데 application-local.yml 파일 이름이 application.yml 로 수정되었는데 요거 잘못 올리신 거 아닌지..?!!

2024-03-03 15:43 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/catch/model/Catch.kt
> +//    val dooingle: Dooingle,
catch에서 dooingle 연관관계를 없애는 거죠..?! 그럼 catch 등록, 삭제할 때 dooingle 쪽에서 관리해줘야 하니까 쪼끔 번거로울 수도 있을 것 같다는 생각이 들긴 하는데 다진님 편하신 대로 하시죠!! ❤️

2024-03-03 15:43 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/catch/service/CatchService.kt
>          catchRepository.save(catch)
이 로직 transactional 어노테이션 없이도 작동하나요??! 필요할 것처럼 보이는데(제가 틀렸을 수 있습니다..!!) 테스트해보셨나용..?!!

2024-03-03 15:43 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleController.kt
> +        @RequestParam loginUserId: Long // TODO : 로그인한 유저의 ID (추후 인증/인가 구현되면 변경)
흠.. 지금 정책상으로는 뒹글 페이지가 나/타인 에 의해서 보여지는 내용이 다르지 않으니까 지금은 loginUserId가 따로 필요하지 않은 것 같긴 합니당... 🤔 나중에 인가 필요한 기능이 추가되면 모르겠지만..!

2024-03-03 15:43 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
> +                    },
오 일케 Any 로 리턴해도 응답이 JSON으로 잘 변환되어서 받아지나요?! 😮 해본 적이 없어서..

2024-03-03 15:43 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
> +        return dooingleRepository.findAllByOwner(owner).map { DooingleResponse.from(it) }
요렇게 하면 owner로 dooingle 조회하는 쿼리 나가고 이후에 guest id 별로 user 조회 쿼리 각각 나가고 또 dooingle id 별로 catch 조회 쿼리 각각 나가지 않나요..?!! queryDsl로 조인해서 한 번에 조회하는 게 훨씬 효율적일 것 같습니다..!! 🥹

2024-03-04 02:02 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/catch/service/CatchService.kt
>          catchRepository.save(catch)
스웨거 돌릴때 문제없이 돌아갔습니당.........!

2024-03-04 02:03 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/catch/model/Catch.kt
> +//    val dooingle: Dooingle,
양방향 하지 말래서 단방향으로 하려다 보니 캐치가 뒹글을 갖고 있는게 아니라 뒹글이 캐치를 갖고있는게 뭔가 정석적인거 같아서 바꿔봤는데 고민을 좀 더 해보겠습니당..❤️

2024-03-04 02:04 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
> +                    },
네!!스웨거에서 콘텐트에 삭제된 캐치라고 리스폰스 잘 뜨더라구용..?!

2024-03-04 02:55 UTC, rugii913 approved these changes

2024-03-04 02:55 UTC, rugii913 commented on src/main/resources/application.yml
스프링 실행 환경 구성 파일 관련해서는 나중에 다시 전체적으로 설명드리겠습니다.
전체적인 협의가 필요한 부분이기도 합니다.
지금은 크게 상관 없지만, 나중에는 보안 문제도 걸려있어서 application.yml 파일은 되도록 수정하지 않는 게 좋을 것 같습니다.

2024-03-04 02:56 UTC, rugii913 commented
application-local.yml vs. application.yml 파일 때문에 dev와 충돌 발생 중입니다.

2024-03-04 02:58 UTC, rugii913 requested changes
~application-local.yml vs. application.yml 파일 때문에 dev와 충돌 발생 중입니다.~
해결 완료

2024-03-04 03:36 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/catch/model/Catch.kt
> +//    val dooingle: Dooingle,
앗 저는 다대일 관계에서 보통 일대다 단방향이 아니라 다대일 단방향으로 하는 걸 생각하고 말씀드린 거였는데 찾아보니까 일대일 관계에서는 외래키가 대상이 되는 테이블에 있는 경우에는 양방향만 가능하다고 하네요?!
https://wildeveloperetrain.tistory.com/186
그래서 결론은 1. 이 entity대로 한다면 erd에서 dooingle이 catch id를 가지도록 수정 2. 현 erd 대로 간다면 entity 양방향으로 수정
저는 둘 다 좋습니다!!❤️

2024-03-04 03:38 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/catch/service/CatchService.kt
>          catchRepository.save(catch)
오 그렇군요!! dooingle에 catch_id 가 안 들어가지 않을까 생각했는데 들어가나 보군요..!!ㅎㅎ

2024-03-04 03:39 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
> +                    },
오오 그렇군요!! 좋구만요!! 잘 구현하셨네요!! 😊

2024-03-04 06:25 UTC, rugii913 approved these changes

2024-03-04 16:42 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/catch/model/Catch.kt
> +//    val dooingle: Dooingle,
양방향으로 수정하겠습니당!!

2024-03-06 11:04 UTC, adorecamus reviewed
고생하셨습니다!! 🥹 일단 이것만 수정해서 머지하고 다시 이슈 올려서 고치죠..!! 🥹

2024-03-06 11:04 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/model/Dooingle.kt
> +    @JoinColumn(name = "catch_id")
JoinColumn 없애고 OneToOne에서 mappedBy 로 dooingle 명시해줘야 합니다!! 🥹

2024-03-06 11:04 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
> +            if (list.size < 6) list else list.dropLast(1),
6보다는 pageable.pageSize 가 유지보수하기 편하겠네요!! 🥹

2024-03-06 11:22 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/dooingle/model/Dooingle.kt
> +    @JoinColumn(name = "catch_id")
넵!!!!!!!

2024-03-06 11:22 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
> +            if (list.size < 6) list else list.dropLast(1),
넵!!!!!!!!!🫡

2024-03-06 14:35 UTC, adorecamus approved these changes
이야아 고생하셨습니다!! 머지해버리시죠!!!

2024-03-06 14:35 UTC, adorecamus commented on src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
> +            if (list.size < selectSize) list else list.dropLast(1),
개떡처럼 말해도 찰떡처럼 알아듣는 다진님~!!! 👍

2024-03-06 15:02 UTC, kDAJIN commented on src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
> +            if (list.size < selectSize) list else list.dropLast(1),
다 유민님의 꼼꼼한 리뷰 덕분이랍니다!!!!!❤️팀장님짱!!!!👍

2024-03-06 15:02 UTC, merged