Feat: 카카오 로그인 및 회원가입
dooingledooingle/dooingle pull request #39
Opened 2024-03-06 14:58 UTC by adorecamus

## 연관 이슈
- closes #34

## 해당 작업을 한 동기/이유는 무엇인가요?
- 카카오 계정으로 사용자 인증을 수행하고 간편하게 회원가입/로그인하는 기능을 구현했습니다.

## 리뷰어에게 작업 또는 변경 내용을 상세히 설명해주세요
- [x] 카카오 계정으로 사용자 인증 후 사용자 정보로 회원가입/로그인하는 기능
    - OAuth2 Client 사용하지 않고 구현 (문제 발생 시 흐름을 파악하기 원활하도록)
    - 추후 다른 소셜 로그인으로 확장할 수 있도록 OAuth2Client 인터페이스로 생성
    - OAuth2ClientService - 리소스 제공자 관련 로직, OAuth2LoginService - 우리 서비스 처리 로직
    - RestClient bean 등록, http 요청 보낼 때 RestClient 이용
- [x] JWT 토큰 발급
  - JWT 라이브러리 추가
  - 소셜 로그인 완료 후 JWT 액세스 토큰 발급
- [x] User Entity 삭제, SocialUser Entity로 대체
- [x] OAuth2, JWT property 추가

2024-03-06 15:04 UTC, adorecamus commented
User를 SocialUser로 대체하면서 엄청난 충돌이 생길 것으로 예상하기 때문에.... 다른 PR들 머지된 후에 충돌 해결해서 다시 커밋하겠습니당❤️

2024-03-07 01:20 UTC, rugii913 approved these changes
고생 많으셨습니다!

2024-03-07 01:23 UTC, rugii913 requested changes
충돌 발생 해결이 필요합니다

2024-03-07 03:19 UTC, kDAJIN commented
뭔가 제가 머지한 팔로우 브랜치에서 꼬인거 같습니다ㅠㅠㅠ최대한 한시전에 해결하겠습니다!!!!!!!!!!!!!!!!!!ㅠㅠㅠㅠㅠㅠ

2024-03-07 03:36 UTC, adorecamus commented
> 뭔가 제가 머지한 팔로우 브랜치에서 꼬인거 같습니다ㅠㅠㅠ최대한 한시전에 해결하겠습니다!!!!!!!!!!!!!!!!!!ㅠㅠㅠㅠㅠㅠ

앗 아녀요 다진님!!!! 제가 해결하면 됩니다!!!!!!

2024-03-07 03:53 UTC, kDAJIN approved these changes

2024-03-07 05:24 UTC, rugii913 approved these changes

2024-03-07 05:31 UTC, nohhayeong approved these changes
확인했습니당

2024-03-07 05:32 UTC, merged